name: Pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project dependencies
        pip install numpy torch torchvision opencv-python Pillow PyQt6 python-doctr psutil pynvml gputil
        # Install additional dependencies if requirements.txt exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Rename pylint config
      run: |
        if [ -f sample_lint.txt ]; then mv sample_lint.txt .pylintrc; fi
    
    - name: Analysing the code with pylint
      run: |
        echo "Running pylint to check code quality, style, and potential bugs..."
        pylint $(git ls-files '*.py') --output-format=text --reports=yes --score=yes
        echo "Pylint analysis completed. Check the logs above for any issues found."
